image:
  file: .gitpod.Dockerfile
tasks:
  - name: Dependencies
    init: |
      eval $(ssh-agent)
      chmod 600 tests/fixtures/tests
      ssh-add tests/fixtures/tests
      docker-compose pull
  - name: Build
    init: make
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - editorconfig.editorconfig
    - hashicorp.terraform
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
