image:
  file: .gitpod.Dockerfile
tasks:
  - name: Go dependencies
    init: |
      go install honnef.co/go/tools/cmd/staticcheck@latest \
      go install github.com/go-delve/delve/cmd/dlv@latest
  - name: Dependencies
    init: |
      chmod 600 tests/fixtures/tests
      ssh-add tests/fixtures/tests
      docker-compose pull
  - name: Build
    init: make
vscode:
  extensions:
    - golang.go
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - editorconfig.editorconfig
    - hashicorp.terraform
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
